# Site settings
title: Adrian Yi's Personal Page
email: a@adrianyi.com
description: > # this means to ignore newlines until "baseurl:"
  Personal page to showcase my work!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://adrianyi.com/" # the base hostname & protocol for your site
permalink: '/:year/:month/:title.html' # link for posts
version: 2.0.1

# User setting
owner: Adrian Yi
email: a@adrianyi.com
facebook_username:
twitter_username:
linkedin_username: adrianyi
github_username: adrianyi
address: San Jose, CA
#  - line: 590 Commonwealth Ave. Room-236
#  - line: Boston, MA 02215
  # Feel free to add more lines here
#telephone: 617-353-5813
copyright: Adrian Yi
headshot: /img/headshot.jpg
resume: /AdrianYi_resume.pdf

# API settings
google_api_key:

# Build settings
markdown: kramdown

# Current project
current_project: Working on D3, databases, and computer vision projects.
# Reproduce results from <a href="https://arxiv.org/abs/1612.08242">YOLO9000</a> using a different CNN architecture
